# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf44e10d232e92d7654ca6646dd857ac6e6ca51038b215df638cbea857c75aab8d987a3c206bb446b5dbe94a38ba3bd343ddc514017e0cd1a077bce87039d82f

test:
  secret_key_base: 92188f774fc74ff1a36c65bc7a027091637c3b14a47e0f2a9ed2f03f817bb5cd605d0f144fc163adfb18161cfb5dd71541fd56ec865b327831d2314b7919717b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
